deploy:
  provider: releases
  api_key:
    secure: K/sZGfRwu/9nyqqeP1dBPGKzp3XL+MU9EcQQO4Xh0i3QOpBWnKISs1/riQOUl4RVmRkuGMHDz+HDxWr5YI+9SspWFDV0APVM9rYEu3dQYB4jQNyLDI77dpaxPi9a5rDU642Iw/2/5nRAiQIPnkMSzguDH/ec/7D6BH+71t5f0BOMqvFPJ3i5fiKe4s8JUOufH3ozN1RM4xxTPYlPJySwOq6HF6JOm5zT/ddAt9akF/6fhGPZ32LL3boAVXhwy/gspP9BtUraIPFw8BxDn6MbDWc4U9/XBmZwnYS1MNCR8Xqri+UCamXWXenTgLsY83pLPeKeqSuvUEC4VOxyfLGkJ1WiOmCXEpQ0JLgDgAMG8RGdkY3XrjhIB+0T4Ru0mLRdFUcOch8RFUqxMZ1wy0cV/OGL1kpZSDSIUgFEJh1SpQRhyACXXWrHMxU1fU8ZQt5WGOpWAaHMWBVxIvSzdRyy3JxiNE5QgWtrWiGcVJ4ZtxqR6TWKIDVqq1P+FYCzEGGhJhxl0VxWwELLRpikdRQHb5teef1ieMhTyo1mIvq6k4qKtRFROzbqA56TRBfE4Y6GN1NgqLnKNEsTlb3mHOYmb8dBco1uRUj3CcTB7gt+2iq+oMXCbWzjhiqeg2mUh7hw6PbEhs3jjRLO+j37T6nd5dJsegezqRJFyirwvxnPxrY=
  on:
    repo: Hexer10/Travis-TestRepo
